name: USOM Seperator

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Python script
        run: |
          python USOMSeperator.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ipv4.txt domain.txt
          git commit -m 'Update IPs and domains'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.USOM_SECRET }}
